### ISSUE TITLE
TypeScript definition file error

### ISSUE THREAD

**Issue by JoBrad** [onury/jsonc#1]
I get this TypeScript error when building a script using your library: 
```
A 'declare' modifier is required for a top level declaration in a .d.ts file.
```
Looks like you just need `declare` right before your `class jsonc` statement on line 19 of the `jsonc.d.ts` file.

**Comment by onury** [comment]
Hi. See [this line](https://github.com/onury/jsonc/blob/master/lib/jsonc.d.ts#L19). `declare` already comes before `class jsonc`.
Besides, the `.d.ts` file is generated by TS compiler, it's not handwritten.
Are you sure the source to that error comes from `jsonc`?

**Comment by JoBrad** [comment]
Hi - I made the cardinal mistake of not checking the version of your package that my NPM module was using. Apologies :)

**Comment by onury** [comment]
No problem at all.
I assume it works as expected once you install the latest version of jsdoc.
