### ISSUE TITLE
Comparison with JSON5

### ISSUE THREAD

**Issue by octogonz** [onury/jsonc#2]
How does JSONC compare with [JSON5](https://json5.org/)?

If I simply want to put code comments in my .json files and have GitHub perform syntax highlight correctly, is it more "standard" to change the file extensions to .jsonc or .json5? :-)

**Comment by onury** [comment]
- `JSON5` is a proposed sub-set of `JSON` spec. It has some extra features other than comments support.
- `JSONC` is just `JSON` with comments.
- `jsonc` (this) is a library supporting `JSON` with comments and many other [features](https://onury.io/jsonc/api).

How GitHub treats JSON files is out of scope of this library.
See [this](https://github.com/github/linguist/issues/4153) and [this](https://gist.github.com/DamianEdwards/31d2457737304ca73556) and [more](https://www.google.com/search?q=github+highlight+json+with+comments&oq=github+highlight+json+with+comments)..
